# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3103c04c09d1260446850df6cdf2b421a12e7fbfe3577242775e0f4fb5bf22cad1d34ad82e38dddba5471ce078e509c9e3783043351844bae17b5c1227fe742

test:
  secret_key_base: 12657a6e5b4904e3da72de475b4ee00ff5746ecf90bc224aceec3e233a8c1a20694f03ac584c8a00711a5d489ec1e7965ac0b584423741d34aa078dd9a5918a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
